'use strict';

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const DARK_TOKENS = path.join(ROOT, 'tokens', 'colors.dark.yml');

// Custom-properties files that must receive the runtime `[data-bs-theme]` block.
const CP_TARGETS = ['colors.custom-properties.css', 'index.custom-properties.css'];
// SCSS files that must receive the compile-time `$*-dark` variable block.
const SCSS_TARGETS = ['colors.scss', 'index.scss'];

// Marker comments so each generated block is unambiguously identifiable and
// re-strippable (kept distinct per form).
const BEGIN = '/* dark-mode: generated by scripts/append-dark.js — do not edit by hand */';
const SELECTOR = '[data-bs-theme="dark"]';

/** Convert `#rrggbb` (or `#rgb`) to theo's `rgb(r, g, b)` output form. */
function hexToRgb(hex) {
  const m = /^#?([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(String(hex).trim());
  if (!m) {
    throw new Error(`Invalid hex color in colors.dark.yml: "${hex}"`);
  }
  let h = m[1];
  if (h.length === 3) {
    h = h.split('').map((c) => c + c).join('');
  }
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `rgb(${r}, ${g}, ${b})`;
}

/**
 * Extract the ordered list of color custom-property names from a light `:root`
 * block. We only consider `--janus-color-*` and `--janus-disabled-button-*`.
 * Non-color custom properties (spacing/type/etc.) are ignored — no dark axis.
 */
function extractColorPropNames(css) {
  const rootMatch = css.match(/:root\s*\{([\s\S]*?)\}/);
  if (!rootMatch) {
    throw new Error('Could not locate :root block in generated CSS.');
  }
  const names = [];
  const re = /--(janus-color-[a-z0-9-]+|janus-disabled-button-[a-z0-9-]+)\s*:/g;
  let m;
  while ((m = re.exec(rootMatch[1])) !== null) {
    names.push(m[1]);
  }
  return names;
}

/**
 * Extract the ordered list of color SCSS variable names (without the leading
 * `$`) from an SCSS file: `$janus-color-*` / `$janus-disabled-button-*`.
 */
function extractColorScssNames(scss) {
  const names = [];
  const re = /^\$(janus-color-[a-z0-9-]+|janus-disabled-button-[a-z0-9-]+)\s*:/gm;
  let m;
  while ((m = re.exec(scss)) !== null) {
    names.push(m[1]);
  }
  return names;
}

/** Remove any previously-appended dark block (idempotency). Form-agnostic. */
function stripPreviousDarkBlock(text) {
  const idx = text.indexOf(BEGIN);
  if (idx === -1) return text;
  return text.slice(0, idx).replace(/\s*$/, '\n');
}

/** Build the runtime `[data-bs-theme="dark"]` custom-properties block. */
function buildDarkCpBlock(orderedNames, darkValues) {
  const lines = [BEGIN, `${SELECTOR} {`];
  orderedNames.forEach((name) => {
    lines.push(`  --${name}: ${hexToRgb(darkValues[name])};`);
  });
  lines.push('}', '');
  return lines.join('\n');
}

/** Build the compile-time `$janus-color-<name>-dark` SCSS block. */
function buildDarkScssBlock(orderedNames, darkValues) {
  const lines = [
    BEGIN,
    '// Compile-time dark-axis mirror of the light $janus-color-* variables.'
  ];
  orderedNames.forEach((name) => {
    lines.push(`$${name}-dark: ${hexToRgb(darkValues[name])};`);
  });
  lines.push('');
  return lines.join('\n');
}

/** Process one file: strip prior block, validate coverage, append fresh block. */
function processFile(file, extractNames, buildBlock, darkValues) {
  const filePath = path.join(DIST, file);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Expected build artifact missing: ${filePath}. Run the gulp build first.`);
  }

  const original = fs.readFileSync(filePath, 'utf8');
  const base = stripPreviousDarkBlock(original);
  const names = extractNames(base);

  // Coverage guard: every light color token must have a dark value.
  const missing = names.filter((n) => !(n in darkValues));
  if (missing.length) {
    throw new Error(
      `[${file}] Missing dark value(s) for: ${missing.join(', ')} (add to tokens/colors.dark.yml).`,
    );
  }
  const known = new Set(names);
  const orphans = Object.keys(darkValues).filter((k) => !known.has(k));

  const block = buildBlock(names, darkValues);
  const next = `${base.replace(/\s*$/, '\n')}\n${block}`;
  fs.writeFileSync(filePath, next, 'utf8');

  console.log(
    `[append-dark] ${file}: appended ${names.length} dark tokens` +
      (orphans.length ? ` (note: ${orphans.length} unused dark value(s): ${orphans.join(', ')})` : ''),
  );
}

function main() {
  const darkDoc = yaml.safeLoad(fs.readFileSync(DARK_TOKENS, 'utf8'));
  const darkValues = (darkDoc && darkDoc.dark) || {};

  // 1. Runtime custom properties.
  CP_TARGETS.forEach((file) => processFile(file, extractColorPropNames, buildDarkCpBlock, darkValues));
  // 2. Compile-time SCSS variables.
  SCSS_TARGETS.forEach((file) => processFile(file, extractColorScssNames, buildDarkScssBlock, darkValues));
}

main();
